dw/models.py
from dw import db
from datetime import datetime
from sqlalchemy.orm import relationship

class Name(db.Model):
    __tablename__ = 'names'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    last_updated = db.Column(db.DateTime, default=datetime.utcnow)
    words = relationship('Word', backref='name', lazy=True, cascade="all, delete-orphan")
    def __repr__(self):
        return f"<Name {self.name}>"

class Word(db.Model):
    __tablename__ = 'words'
    id = db.Column(db.Integer, primary_key=True)
    roll = db.Column(db.Integer, nullable=False) 
    word = db.Column(db.String(120), nullable=False)
    listname_id = db.Column(db.Integer, db.ForeignKey('names.id'), nullable=False)
    def __repr__(self):
        return f"<Word {self.roll}>"

dw/__init__.py
from flask import Flask, redirect, url_for
from flask_migrate import Migrate
from pathlib import Path
from flask_sqlalchemy import SQLAlchemy
import logging
from logging.handlers import RotatingFileHandler

db = SQLAlchemy()
migrate = Migrate()

def create_app(config='config.Config'):
    app = Flask(__name__, instance_relative_config=True)

    app.config.from_object(config)

    try:
        Path(app.instance_path).mkdir(parents=True)
    except FileExistsError:
        pass

    if not app.debug or not app.testing:
        if not Path('logs').exists():
            Path('logs').mkdir()
        file_handler = RotatingFileHandler('logs/dw.log',maxBytes=10240, backupCount=10)
        file_handler.setFormatter(logging.Formatter('%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'))
        file_handler.setLevel(logging.INFO)
        app.logger.addHandler(file_handler)
        app.logger.setLevel(logging.INFO)
        app.logger.info('dw startup')

    @app.route('/')
    def go_home():
        return redirect(url_for('generate.diceware'))
    
    db.init_app(app)
    migrate.init_app(app, db)

    from dw.about import bp as about_bp
    app.register_blueprint(about_bp, url_prefix='/about')

    from dw.generate import bp as gen_bp
    app.register_blueprint(gen_bp, url_prefix='/generate')

    from dw.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from dw.commands import init_db_command, clear_db_command
    app.cli.add_command(init_db_command)
    app.cli.add_command(clear_db_command)
    
    return app

from dw import models

dw/about/__init__.py
from flask import Blueprint

bp = Blueprint('about', __name__)

from dw.about import routes

dw/about/routes.py
from flask import render_template, url_for
from dw.about import bp
from dw.models import Name

@bp.route('/diceware')
def diceware():
    curr_lists = Name.query.all()
    return render_template('about/diceware.html', names=curr_lists)

@bp.route('/project')
def project():
    return render_template('about/project.html')

@bp.route('/author')
def author():
    return render_template('about/author.html')

@bp.route('lists/<listname>')
def get_list(listname):
    curr_lists = Name.query.filter(Name.name==listname).first()
    return render_template('about/lists.html', name=curr_lists.name, rolls=curr_lists.words)

dw/generate/__init__.py
from flask import Blueprint

bp = Blueprint('generate', __name__)

from dw.generate import routes

dw/generate/routes.py
from flask import render_template, url_for, jsonify
from dw.models import Name
from dw.generate import bp

@bp.route('/diceware')
def diceware():
    names = Name.query.all()
    return render_template('generate/diceware.html', names=names)

@bp.route('/lists')
def get_data():
    names = Name.query.all()
    dwLists = {}
    for i,name in enumerate(names):
        dwLists[name.name] = {}
        for word in names[i].words:
            dwLists[name.name][word.roll] = word.word

    return jsonify(dwLists)

dw/templates/about/author.html
{% extends 'base.html' %}

{% block aa %}active{% endblock %} 

{% block ar %}<span class="sr-only">(current)</span>{% endblock %}

{% block header %}
    <h1 class="h1 text-center">{%block title %}About Me{% endblock %}</h1>
{% endblock %}

{% block content %}
    <div class="container text-left">
        <div class="row">
            <div class="col"></div>
            <div class="col"></div>
                <p>
                    Hi, my name is Anthony. I'm a data analyst who likes to dabble in software on the side. Considering the basic password requirements for your average job today, it seemed like a fun and useful project to build a simple app to knock off some of the legwork ever 30 to 90 days. 
                </p>
                <p>
                    It was an enjoyable experience building this, and if there is any feedback, bugs or issues, please don't hesitate to reach out to me on <a class="text-info" target="_blank" rel="noreferrer noopener" href="https://github.com/GongJunior/dw-Web">Github.</a>
                </p>
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

dw/templates/about/diceware.html
{% extends 'base.html' %}

{% block dwa %}active{% endblock %} 

{% block dwr %}<span class="sr-only">(current)</span>{% endblock %}

{% block header %}
    <h1 class="h1 text-center">{%block title %}What is Diceware{% endblock %}</h1>
{% endblock %}

{% block content %}
    <div class="container text-center">
        <p class="text-left">
            Diceware is a system used to generate pasphrases. The strength of Diceware lies in the idea that a group of randomly rolled standard words is very inefficient for a computer to guess, but easy to remember. The general idea of the process is as follows:
        </p>
        <ol class="text-left">
            <li>Acquire a standard dice and <a class="text-info" target="_blank" rel="noreferrer noopener" href="https://theworld.com/%7Ereinhold/diceware.wordlist.asc">list.</li></a>
            <li>Roll the die 5 times, recording each roll in order.</li>
            <li>Select a word from the list corresponding to the rolls in step 2</li>
            <li>Repeat steps 2 & 3 until you're satisfied with the number of words</li>
        </ol>
        <p class="text-left">
            Obviously with pen and paper this would be a very time consuming process to go through every time you need a password, but would offer true randomness in password generation. While apps like this cannot truly replicate the randomness found in the real world, their purpose is to try to strike a balance between convenience and security. 
        </p>
        <div class="row justify-content-center">
            <h2 class="text-center">Additional Resources</h2>
        </div>
        <div class="row">
            <div class="col">
                <h3 class="text-center">Required Post</h3>
                <p class="text-center">XKCD: <a class="text-info" target="_blank" rel="noreferrer noopener" href="https://xkcd.com/936/">https://xkcd.com/936/</a></p>
                <a target="_blank" rel="noreferrer noopener" href="https://imgs.xkcd.com/comics/password_strength.png"> <img class="img-fluid" src=https://imgs.xkcd.com/comics/password_strength.png alt="Password Strength"/></a>
            </div>
            <div class="col">
                <h3 class="text-center">Links</h3>
                <ul class="text-left">
                    <li>EFF: <a class="text-info" target="_blank" rel="noreferrer noopener" href="https://www.eff.org/dice">https://www.eff.org/dice</a></li>
                    <li>Rempe: <a class="text-info" target="_blank" rel="noreferrer noopener" href="https://www.rempe.us/diceware/#eff">https://www.rempe.us/diceware/</a></li>
                    <li>Reinhold: <a class="text-info" target="_blank" rel="noreferrer noopener" href="https://theworld.com/~reinhold/diceware.html">https://theworld.com/~reinhold/diceware.html</a></li>
                    {% for name in names %}
                    <li>{{ name.name }}: <a class="text-info" target="_blank" rel="noreferrer noopener" href="{{ url_for('about.get_list', listname=name.name) }}">{{ name.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

{% endblock %}

dw/templates/about/lists.html
{% extends 'base.html' %}

{% block header %}
    <h1 class="h1 text-center">{%block title %}{{ name }}{% endblock %}</h1>
{% endblock %}

{% block content %}
    <div class="container text-center">
        {% for roll in rolls %}
            <span>{{ roll.roll }}</span>
            <span>{{ roll.word }}</span>
            <br/>
        {% endfor %}
    </div>
{% endblock %}

dw/templates/about/project.html
{% extends 'base.html' %}

{% block pa %}active{% endblock %} 

{% block pr %}<span class="sr-only">(current)</span>{% endblock %}

{% block header %}
    <h1 class="h1 text-center">{%block title %}Purpose of this Project{% endblock %}</h1>
{% endblock %}

{% block content %}
    <div class="container text-left">
        <p>
            The purpose of this project was to make an easy access, client-side, roll generator for my personal needs. This was heavily inspired from <a class="text-info" target="_blank" rel="noreferrer noopener" href="https://www.rempe.us/diceware/">https://www.rempe.us/diceware/</a>, with a few divergences for my own convenience. I encourage you to check out this site as there is a lot of solid information if you'd like to learn more.
        </p>
        <p>
            Currently, this tool has a couple simple uses.  First, the <a class="text-info" href="{{ url_for('generate.diceware') }}">main</a> page can be used to generate a passphrase or a set of rolls. Secondly, if you'd like to fetch the entire dataset in JSON format, you can access <a class="text-info" href="{{ url_for('generate.get_data') }}">{{ url_for('generate.get_data', _external=True) }}</a>.  This file contains all loaded lists in an easily parsable format. Lastly, if you'd like run the app locally, this project can be installed from <a class="text-info" target="_blank" rel="noreferrer noopener" href="https://github.com/GongJunior/dw-Web">Github.</a> Running it locally will allow you customize your own list set if necessary.
        </p>
    </div>
{% endblock %}

dw/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!--Required meta tags-->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <meta name="description" content="Diceware based passphrase generator">

        <!--Bootstrap CSS-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <!--Local CSS Styles-->
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
        {% block pagestyle %}{% endblock %}

        <title>{% block title %} {% endblock %} - Diceware</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{{ url_for('generate.diceware') }}">Diceware</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item {% block dwa %} {% endblock %}">
                        <a class="nav-link" href="{{ url_for('about.diceware') }}">What {% block dwr %} {% endblock %}</a>
                    </li>
                    <li class="nav-item {% block pa %} {% endblock %}">
                        <a class="nav-link" href="{{ url_for('about.project') }}">Why {% block pr %} {% endblock %}</a>
                    </li>
                    <li class="nav-item {% block aa %} {% endblock %}">
                        <a class="nav-link" href="{{ url_for('about.author') }}">Who {% block ar %} {% endblock %}</a>
                    </li>
                </ul>
            </div>
        </nav>

        <section class="content">
            <header>
                {% block header %}{% endblock %}
            </header>
            {% block content %}{% endblock %}
        </section>

        <!--Required bootstrap javascript-->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

        <!--Local js assets-->
        <script src="{{ url_for('static', filename='base.js') }}"></script>
        {% block pagejs %}{% endblock %}
    </body>
</html>

dw/templates/generate/diceware.html
{% extends 'base.html' %}

{% block header %}
    <h1 class="h1 text-center">{%block title %}Diceware Passphrase Generator{% endblock %}</h1>
{% endblock %}

{% block content %}
    <div class="text-center" id="intro">Loading Assets</div>
    <br>
    <form class="form-inline justify-content-center">
        <label class="sr-only" for="numOfWords">Number of Words</label>
        <div class="form-group mb-3 mr-3">
            <select class="form-control" id="numOfWords">
                {% for i in range(3,14) %}
                    <option>{{ i }}</option>
                {% endfor %}
            </select>
        </div>
        <label class="sr-only" for="dropdownMenuButton">List Options</label>
        <div class="dropdown mb-3">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Select List
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                {% for name in names %}
                    <a class="dropdown-item" href="#" onclick='generateResult("{{ name.name }}")'>{{ name.name }}</a>
                {% endfor %}
            </div>
        </div>
    </form>
    <br/>

    <label class="sr-only" for="output">Diceware Output</label>
    <div class="card mx-auto" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">Passphrase Result</h5>
            <h6 id="listused" class="card-subtitle mb-2 text-muted"></h6>
            <p id="passphrase" class="card-text mb-0"></p>
            <p id="allrolls" class="card-text"></p>
        </div>
    </div>

    <script>
        window.onload = (event) => {
            $.get("{{ url_for('generate.get_data') }}",function(data){
                loadDicewaretoMemory(data)
            }).done(function(){
                $("#intro").text("Network can be disabled while generating phrases")
            }).fail(function(){
                $("#intro").text("ERROR: Could not load assets")
            });
        };
    </script>
{% endblock %}